# Generated by Django 3.2.18 on 2023-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcase',
            name='error_01',
            field=models.BooleanField(max_length=30, verbose_name='異常０１'),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='error_02',
            field=models.BooleanField(max_length=30, verbose_name='異常０２'),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='error_03',
            field=models.BooleanField(max_length=30, verbose_name='異常０３'),
        ),
    ]
