# Generated by Django 3.2.18 on 2023-03-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_auto_20230329_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalModel',
        ),
    ]
