# Generated by Django 3.2.18 on 2023-03-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_delete_animalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
